### ISSUE TITLE
Undefined variable: index . Invalid expression: [a:string[index:]]

### ISSUE THREAD

**Issue by srzlt** [skywind3000/quickmenu.vim#1]
getting this error when hitting F12

`Error detected while processing function quickmenu#toggle[24]..<SNR>187_menu_expand[2]..<SNR>187_expand_text:
line    6:
E121: Undefined variable: index:
E15: Invalid expression: [a:string[index:]]`

**Comment by skywind3000** [comment]
That's impossible, index has been defined in line [#495](https://github.com/skywind3000/quickmenu.vim/blob/d03ad08aa084b04722607455e8ea48af1a7ee5fa/autoload/quickmenu.vim#L495). are you using the latest version ? 1.1.13.
Would you please provide me your `quickmenu#append` config ?

**Comment by skywind3000** [comment]
I see, you were running vim 7.3 right ??

**Comment by skywind3000** [comment]
Please update to the latest release.
incompatible issues have been fixed.

**Comment by srzlt** [comment]
I installed the plugin via vundle. The latest vommit I see in my local repo is:
`commit d03ad08aa084b04722607455e8ea48af1a7ee5fa
Author: skywind3000 <skywind3000@163.com>
Date:   Fri Jul 14 01:05:05 2017 +0800

    update quickmenu`

I also changed the Key to F8 but see the same issue there.

I use vim 7.4

`⇒  vim --version
VIM - Vi IMproved 7.4 (2013 Aug 10, compiled Apr  4 2017 18:14:54)`

**Comment by skywind3000** [comment]
d03ad08 is still incompatible with earlier vim 7.4, see [here](https://github.com/skywind3000/quickmenu.vim/commits/master)

you need `:PluginUpdate` and restart vim

**Comment by srzlt** [comment]
@skywind3000 yep, that helped - thanks!
