### ISSUE TITLE
How to open the quickmenu on the right instead of on the left?

### ISSUE THREAD

**Issue by lfv89** [skywind3000/quickmenu.vim#2]
Thanks for this great plugin, I'm in love with it.

Couldn't find the answer for this question in the README nor in the source code though.

**Comment by skywind3000** [comment]
It will popup on the left if your `nosplitright` has been set.
I have fixed it. you can try the latest release.
quickmenu will always popup on the right, no matter `nosplitright` is set or unset, unless you have a `T` in the `g:quickmenu_options`.

**Comment by lfv89** [comment]
❤️
