### ISSUE TITLE
Use a funcref instead of a string in quickmenu#append()

### ISSUE THREAD

**Issue by tjdevries** [skywind3000/quickmenu.vim#6]
Hi, awesome plugin :smile:

I'm wondering if it would be possible to use a function reference or lambda for `quickmenu#append()`.

For example:

```vim
function! ExampleFunc(arg) abort
  return arg + 1
endfunction

call quickmenu#append('call funcref', funcref('ExampleFunc', [10]))
```

Thanks

**Comment by tjdevries** [comment]
this is mostly so that I can pass an argument (like a dictionary) into the function. A better example might be:

```vim
for setting in keys(config_dict)
  " Give the option of a setting for each item:
  call quickmenu#append(
            \ printf('Set: %s.%s', area, setting),
            \ { -> config#set_setting(config_dict, setting, input('New value: ')},
            \ )
endfor
```

**Comment by skywind3000** [comment]
good point, new version released

**Comment by tjdevries** [comment]
Works great for me. I'm using it in my plugin here: www.github.com/tjdevries/conf.vim

It makes great menus now. Autogenerated cause of your wonderful plugin.

![image](https://user-images.githubusercontent.com/4466899/29073343-ec903fe6-7c10-11e7-83b1-627c233faa09.png)

Having the ability to add descriptions is great for helping people to figure out what the options are. Thanks!

**Comment by tjdevries** [comment]
The code changes became very easy with your change.


```vim
      call quickmenu#append(
            \ printf('Set: %s.%s', area, setting),
            \ funcref('conf#set_setting_prompt', [
                    \ a:script,
                    \ area,
                    \ setting,
                    \ ]),
            \ conf#setting#get_description(a:script, area, setting)
            \ )
```
