### ISSUE TITLE
is there possible to toggle more than one window?

### ISSUE THREAD

**Issue by linkensphere201** [skywind3000/quickmenu.vim#8]
Hi,
thanks for your wonderful and newbie-friendly vim plugin.

[the background]: I'm trying to use this plugin for making a "symbol list window"(just like source-insight) to show all symbols of the editing file. [my conf](https://github.com/quarsars/work_things/blob/master/my_vim_plugin/quarsars.vim)

[the question]: now I'm wondering if there's possible to show more window(a window for symbol-in-current-file listing , another window for symbol-in-the-whole-project searching)
thanks again!

**Comment by skywind3000** [comment]
Absolutely, you can indicate the menu name by the first parameter of `quickmenu#toggle`
and setup different menu by quickmenu#current,

```VimL
call quickmenu#current('symbol-file')
call quickmenu#reset()
call quickmenu#append(...)
...
call quickmenu#current('symbol-project')
call quickmenu#reset()
call quickmenu#append(...)
...
noremap <silent><F11> :call quickmenu#toggle('symbol-file')<cr>
noremap <silent><F12> :call quickmenu#toggle('symbol-project')<cr>
```

And of course, you can re-generate menu content each time before invoking `quickmenu#toggle`

**Comment by linkensphere201** [comment]
awesome!
